export enum TRANSACTION_DIRECTION {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

export enum FINANCE_CATEGORY {
  FLOWER_STOCK = 'FLOWER_STOCK',
  PACKAGING_SUPPLIES = 'PACKAGING_SUPPLIES',
  EMPLOYEE_SALARY = 'EMPLOYEE_SALARY',
  MARKETING = 'MARKETING',
  REFUND = 'REFUND',
  ORDER_PAYMENT = 'ORDER_PAYMENT',
}

export const FINANCE_CATEGORY_LABEL = {
  [FINANCE_CATEGORY.FLOWER_STOCK]: 'Nhập hoa',
  [FINANCE_CATEGORY.PACKAGING_SUPPLIES]: 'Vật tư',
  [FINANCE_CATEGORY.EMPLOYEE_SALARY]: 'Lương nhân viên',
  [FINANCE_CATEGORY.MARKETING]: 'Quảng cáo',
  [FINANCE_CATEGORY.REFUND]: 'Hoa hồng',
  [FINANCE_CATEGORY.ORDER_PAYMENT]: 'Thanh toán đơn hàng',
};
