export enum ORDER_STATUS {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export const ORDER_STATUS_LABEL = {
  [ORDER_STATUS.PENDING]: 'Chưa giao',
  [ORDER_STATUS.DELIVERED]: 'Đã giao',
  [ORDER_STATUS.CANCELLED]: 'Huỷ',
  [ORDER_STATUS.RETURNED]: 'Trả hàng',
};
