export enum ORDER_STATUS {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export const ORDER_STATUS_LABEL = {
  [ORDER_STATUS.PENDING]: 'Chưa giao',
  [ORDER_STATUS.DELIVERED]: 'Đã giao',
  [ORDER_STATUS.CANCELLED]: 'Huỷ',
  [ORDER_STATUS.RETURNED]: 'Trả hàng',
};

export const ORDER_STATUS_COLORS: Record<ORDER_STATUS, string> = {
  [ORDER_STATUS.PENDING]: '#fbbf24',
  [ORDER_STATUS.DELIVERED]: '#22c55e',
  [ORDER_STATUS.CANCELLED]: '#ef4444',
  [ORDER_STATUS.RETURNED]: '#f87171',
};

export enum TRANSACTION_TYPE {
  CASH = 'CASH',
  BANK = 'BANK',
}

export const TRANSACTION_TYPE_LABEL = {
  [TRANSACTION_TYPE.CASH]: 'Tiền mặt',
  [TRANSACTION_TYPE.BANK]: 'Chuyển khoản',
};
